### ISSUE TITLE
Store cached keywords to a JSON file instead of a preference

### ISSUE THREAD

**Issue by piroor** [piroor/secondsearch#10]
There is a warning from too large JSON.

> Warning: attempting to write 6191 bytes to preference extensions.{0AE5CAA4-8BAB-11DB-AF59-ED4B56D89593}.secondsearch.keyword.cache. This is bad for general performance and memory usage. Such an amount of data should rather be written to an external file.

**Comment by piroor** [comment]
Done.

**Comment by Gitoffthelawn** [comment]
Which keywords does it cache, and which does it not?  Or does it just cache every bookmark keyword?

**Comment by piroor** [comment]
All bookmark keywords are cached.

**Comment by Gitoffthelawn** [comment]
OK... maybe when it was stored in prefs.js it was just too limited.  It only showed about 5 of them in the associated pref.
