### ISSUE TITLE
Breaks urlbar autosuggest in Firefox 43

### ISSUE THREAD

**Issue by Gitoffthelawn** [piroor/secondsearch#11]
When installed in Firefox 43, it breaks the urlbar autosuggest feature.

In other words, if the user has a bookmark for github.com, and they type in `gi`, they will no longer see the bookmark as a suggestion in a dropdown list.

**Comment by piroor** [comment]
Any screenshot? Because I don't know the full features of the new location bar, I don't understand what is the problem...

**Comment by Gitoffthelawn** [comment]
Normally, when the user enters text into the Location Bar (starting somewhere around Firefox 2 or even before), any bookmarks/history that match the string are displayed in a dropdown just below the Location Bar.  When Second Search is installed, the dropdown fails to appear.

**Comment by piroor** [comment]
On Firefox 43 on Ubuntu I cannot see such a fatal problem with the master/HEAD. The problem is possibly already fixed but not released yet. Could you try the development build?: http://piro.sakura.ne.jp/xul/xpi/nightly/ (note: you have to turn off the preference "xpinstall.signatures.required" to "false".

**Comment by Gitoffthelawn** [comment]
Here is a screenshot example of the Location Bar with the dropdown:

http://www.tidbits.com/resources/2008-06/Firefox-smart-location-bar.png

(I see you just posted, but this might still be useful to you.)

**Comment by Gitoffthelawn** [comment]
I rebuilt the extension using the commits to inherit.jsm and browser.js.  That seems to fix it!  :-)

I'm surprised no one has reported the issue here or on AMO.

**Comment by Gitoffthelawn** [comment]
Oh wait, hold on, after making those commit, now the Second Search functionality is gone.

**Comment by Gitoffthelawn** [comment]
It looks like the updates fixed this.  Thank you!
