### ISSUE TITLE
Popup no longer working with FF43 on Linux

### ISSUE THREAD

**Issue by IzzySoft** [piroor/secondsearch#14]
Somehow I got it working again on Windows, but cannot reproduce that "fix" on Linux: Entering a search term and pushing the "cursor-up" key opened and navigated the popup menu (until FF42). After updating to FF43, that's no longer working. In fact, it looks as if SecondSearch wasn't there at all: No way to open it with either keyboard or mouse.

And yes, I've updated to the latest version of the addon (1.0.2015122401). Signed version on my Linux machine (doesn't work). On the Windows machine, I'd installed the unsigned version (a day before Mozilla approved and signed). No settings changed. And yeah, that `browser.search.showOneOffButtons` was set to `false` – but AFAIK this has been removed with FF43, and such no longer has any effect. `secondsearch.popup.auto_show` is set to `true` – except for the search engines, all SecondSearch options are set to their defaults.

Even using _Classic Theme Restorer_  to get back the "old search" didn't help.

Anything I could try? Any more details needed from your end?

**Comment by IzzySoft** [comment]
**Update:** I've tried even on a clean profile (with no other addons), no success. Then, inspired by the currently last rating on AMO (stating the latest version not running on FF 43.0.3, and being made with Version 0.9.2015020901) I've installed that version from 02/2015. Works again. So I'll stick with that for know.

Somehow, one of the last changes must have broken it for at least FF43 on Linux (43.0.4 here).

**Comment by piroor** [comment]
Hmm, it still works for me on Ubuntu...

 * Ubuntu 14.04LTS
 * Firefox 43.0.4 (build ID 20160105164030)
 * Second Search 1.0.2015122400a185109
 * DOM Insepector  2.0.16

This is possibly a platform specific issue. Which distribution (and version) are you using?

**Comment by IzzySoft** [comment]
Sorry for missing those details:

* Ubuntu 12.04LTS
* Firefox 43.0.4
* Second Search 1.0.2015122401 (from AMO; not working)
* Second Search 0.9.2015020909.1 (working)

Note: I don't use the Firefox from Ubuntu Repos, but the Mozilla build (from their repo: `deb http://downloads.sourceforge.net/project/ubuntuzilla/mozilla/apt all main`). I'd give your latest devel code a try if you think it helps (maybe with some debug code built in). Thanks to the stupid signing enforcement, things like that are no longer possible soon – but at the moment, I was still able to "permit unsigned addons" (still using a few of those with no chance of getting signed any day, as their devs abandoned them: Keyconfig, Show Chromeless).

Btw: There's another user reporting the same issues at AMO, as pointed out (Fab112 – from whom I took the hint of trying the old version again). Might be useful to find out what he's using (platform/build).

**Comment by piroor** [comment]
Could you tell me the testing result on the official binary? [Download](https://www.mozilla.org/en-US/firefox/all/) and unpack a tarball for Linux, then you'll see a directory "firefox". You'll start the official binary with clean profile, via the command line: `mkdir -p /tmp/firefox-tmp && ./firefox/firefox -no-remote -profile /tmp/firefox-tmp`

**Comment by IzzySoft** [comment]
Sorry for the delay – but I got drowned in work. Meanwhile it looks like your latest update solved the issue for me: First time the search box worked straigt away right with a fresh started FF! Before, I always had to type something in the box, klick the URL bar, click back, type again (the first time after a fresh start, that is). Great! :+1: 

Give me a few days to verify. If I didn't report back within 2 weeks, consider the issue solved (I hope to return here before that to close the issue myself, but you know how things go ;)
