### ISSUE TITLE
ポップアップが出ない件について

### ISSUE THREAD

**Issue by BOACK** [piroor/secondsearch#16]
1.0.2016020301についてですが、残念ながらWindows機でもポップアップは出ませんでした。
ただ、問題の再現はできました。
1. 新規プロファイル作成
2. セカンドサーチをインストール
3. [http://seekr.jp/](http://seekr.jp/)へ行き「ブラウザに追加」
でポップアップが出なくなります。
念のため普段のプロファイルでseekRの検索エンジンを削除するとポップアップが出るようになりました。
seekRにファビコンがないのが問題なのかもしれません。
上記条件で、「起動 -> 検索バー選択 -> 検索ワード入力」のログ（JSのみ）は以下になります。

```
operateSecondSearch
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host] browser.js:297:0
operateSecondSearch
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host] browser.js:297:0
operateSecondSearch
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host] browser.js:297:0
operateSecondSearch
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIURI.host] browser.js:297:0
operateSecondSearch
1454551814241	Services.HealthReport.HealthReporter	WARN	Saved state file does not exist.
```

**Comment by piroor** [comment]
詳しい再現条件について情報をいただきありがとうございます！ こちらでも再現できたので、対策を入れてみました。

 * bc4012a586c5d50f4d2cb2bc755c2611acbdea1b
 * 36258115b2e1f88169b54bb1b470538caba55e5a

**Comment by BOACK** [comment]
nightlyからアップデートしてみたところ、seekRを追加してもポップアップが表示されるようになりました！
ありがとうございました。

**Comment by piroor** [comment]
よかったです！
