### ISSUE TITLE
Wrong layout when selecting view ordered by name

### ISSUE THREAD

**Issue by Dominiquini** [piroor/secondsearch#35]
When using the mode "Ordered by Name", the layout of menu appears to be broken:

Recently Used:
![Ordered by Recently Used](https://user-images.githubusercontent.com/1180808/68031417-61f32a80-fc9a-11e9-9567-9bd446889aca.png)

Name:
![Ordered by Name](https://user-images.githubusercontent.com/1180808/68031410-5ef83a00-fc9a-11e9-9072-40370e491b30.png)

SO: Windows 10
Firefox: 70.0
Second Search: 2.2.3

Thanks

**Comment by piroor** [comment]
Thanks, this should be fixed with the commit: 3927c85c10a4527d9169570341cc723f05163314

**Comment by Dominiquini** [comment]
Thanks!

I'm closing the issue.
